### ISSUE TITLE
Scrivere slides di presentazione su progetto

### ISSUE THREAD

**Issue by Torkin1** [CSW-Teams/MS3-docs#5]
Raccontare sprint per sprint cosa è stato fatto, sia come processo che come codice.
80-90 slides circa, 1h30.

**Comment by Torkin1** [comment]
deve includere sezione sviluppi futuri, con storie non ancora implementate

**Comment by Fanfarillo** [comment]
Issue da tenere aperto perché tornerà utile nell'A.A. 2023/2024

**Comment by Stack-1** [comment]
Issue chiuso dato che il progetto è stato presentato e quindi le slide sono state scritte per lo scorso anno accademico (2022-2023). Per l'anno accademico corrente (2023-2024) non ha senso mantenere aperto questo issue.
